-- 预设公司库:知名公司 + 中英文别名(可重复执行;跑两遍:public 与 demo schema)
-- 用法:PGOPTIONS="-c search_path=public"(或 demo,public)psql ... -f supabase/companies_seed.sql

-- 现有公司补别名
update companies set aliases = v.a from (values
  ('字节跳动', array['ByteDance']),
  ('腾讯', array['Tencent']),
  ('阿里巴巴', array['Alibaba','阿里']),
  ('米哈游', array['miHoYo','HoYoverse']),
  ('网易', array['NetEase']),
  ('美团', array['Meituan']),
  ('快手', array['Kuaishou']),
  ('百度', array['Baidu']),
  ('京东', array['JD','JD.com']),
  ('华为', array['Huawei']),
  ('小米', array['Xiaomi']),
  ('蔚来', array['NIO']),
  ('理想汽车', array['Li Auto','理想']),
  ('大疆', array['DJI']),
  ('携程', array['Trip.com','Ctrip']),
  ('哔哩哔哩', array['Bilibili','B站']),
  ('小红书', array['Xiaohongshu','RED','rednote']),
  ('拼多多', array['Pinduoduo','PDD']),
  ('知乎', array['Zhihu']),
  ('泡泡玛特', array['POP MART','PopMart']),
  ('元气森林', array['Genki Forest','Chi Forest']),
  ('完美世界', array['Perfect World']),
  ('莉莉丝游戏', array['Lilith Games','莉莉丝']),
  ('叠纸游戏', array['Papergames','叠纸']),
  ('心动网络', array['XD Inc','心动','TapTap']),
  ('月之暗面', array['Moonshot AI','Moonshot','Kimi']),
  ('智谱AI', array['Zhipu AI','Zhipu','Z.ai','智谱']),
  ('深度求索', array['DeepSeek']),
  ('MiniMax', array['稀宇科技']),
  ('阶跃星辰', array['StepFun']),
  ('宇树科技', array['Unitree','宇树']),
  ('影石Insta360', array['Insta360','影石']),
  ('得物', array['Dewu','Poizon']),
  ('货拉拉', array['Lalamove','Huolala']),
  ('作业帮', array['Zuoyebang'])
) as v(n, a)
where companies.name = v.n;

-- 新增知名公司(存在即跳过)
insert into companies (name, industry_tags, city_tags, aliases, source) values
  ('OpenAI', '{AI}', '{海外}', '{}', 'builtin'),
  ('Anthropic', '{AI}', '{海外}', '{}', 'builtin'),
  ('Google', '{互联网,AI}', '{海外}', array['谷歌','Alphabet'], 'builtin'),
  ('Microsoft', '{互联网}', '{海外}', array['微软'], 'builtin'),
  ('Apple', '{硬件}', '{海外}', array['苹果'], 'builtin'),
  ('Meta', '{互联网}', '{海外}', array['Facebook','脸书'], 'builtin'),
  ('Amazon', '{互联网,电商}', '{海外}', array['亚马逊','AWS'], 'builtin'),
  ('NVIDIA', '{硬件,AI}', '{海外}', array['英伟达'], 'builtin'),
  ('Tesla', '{汽车}', '{海外}', array['特斯拉'], 'builtin'),
  ('xAI', '{AI}', '{海外}', '{}', 'builtin'),
  ('Mistral AI', '{AI}', '{海外}', array['Mistral'], 'builtin'),
  ('Cursor', '{AI}', '{海外}', array['Anysphere'], 'builtin'),
  ('Vercel', '{互联网}', '{海外}', '{}', 'builtin'),
  ('Stripe', '{互联网}', '{海外}', '{}', 'builtin'),
  ('Shopify', '{电商}', '{海外}', '{}', 'builtin'),
  ('Netflix', '{内容}', '{海外}', array['奈飞'], 'builtin'),
  ('Airbnb', '{互联网,旅行}', '{海外}', array['爱彼迎'], 'builtin'),
  ('Uber', '{互联网}', '{海外}', array['优步'], 'builtin'),
  ('滴滴', '{互联网}', '{北京}', array['DiDi','滴滴出行'], 'builtin'),
  ('蚂蚁集团', '{互联网}', '{杭州}', array['Ant Group','蚂蚁金服','蚂蚁'], 'builtin'),
  ('比亚迪', '{汽车}', '{深圳}', array['BYD'], 'builtin'),
  ('小鹏汽车', '{汽车}', '{广州}', array['XPeng','小鹏'], 'builtin'),
  ('吉利', '{汽车}', '{杭州}', array['Geely','吉利汽车'], 'builtin'),
  ('科大讯飞', '{AI}', '{合肥}', array['iFLYTEK','讯飞'], 'builtin'),
  ('商汤科技', '{AI}', '{上海}', array['SenseTime','商汤'], 'builtin'),
  ('旷视科技', '{AI}', '{北京}', array['Megvii','旷视'], 'builtin'),
  ('零一万物', '{AI}', '{北京}', array['01.AI'], 'builtin'),
  ('面壁智能', '{AI}', '{北京}', array['ModelBest','面壁'], 'builtin'),
  ('硅基流动', '{AI}', '{北京}', array['SiliconFlow'], 'builtin'),
  ('昆仑万维', '{互联网,AI}', '{北京}', array['Kunlun','Skywork'], 'builtin'),
  ('三七互娱', '{游戏}', '{广州}', array['37 Interactive'], 'builtin'),
  ('游戏科学', '{游戏}', '{深圳,杭州}', array['Game Science'], 'builtin'),
  ('瑞幸咖啡', '{消费}', '{厦门}', array['Luckin','luckin coffee','瑞幸'], 'builtin'),
  ('联想', '{硬件}', '{北京}', array['Lenovo'], 'builtin'),
  ('OPPO', '{硬件}', '{深圳}', '{}', 'builtin'),
  ('vivo', '{硬件}', '{东莞}', '{}', 'builtin'),
  ('荣耀', '{硬件}', '{深圳}', array['HONOR'], 'builtin'),
  ('中兴', '{硬件,通信}', '{深圳}', array['ZTE','中兴通讯'], 'builtin')
on conflict (name) do update set aliases = excluded.aliases, industry_tags = excluded.industry_tags;
